# Skeleton of a terraform/anislbe project with GitLab-ci/runner 
image:
  name: zyker/toolbox:v0.0.3

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform

before_script:
  - mkdir ~/.aws
  - cp configuration/* ~/.aws
  - cd infrastructure
  - python build-terraform.py -i env-developement.yml -e env-developement.txt -o env-developement.tf
  - mkdir /opt-gitlab-runner
  - cp tf_files/env-developement.tf /opt-gitlab-runner
  - cd /opt-gitlab-runner
  - terraform init
  
stages:
  - build
  - deploy

plan:
  stage: build
  script:
    - terraform plan -out=$PLAN
  artifacts:
    name: plan
    paths:
      - $PLAN
apply:
  stage: deploy
  environment:
    name: production
  script:
    - terraform apply -input=false $PLAN
  dependencies:
    - plan
  when: manual
  only:
    - master

